include device/lge/msm7x27-common/BoardConfigCommon.mk

TARGET_KERNEL_CONFIG := gelato-perf_defconfig
TARGET_KERNEL_SOURCE := kernel/lge/gelato

BOARD_KERNEL_CMDLINE := mem=477M console=ttyMSM2,115200n8 androidboot.hardware=gelato no_console_suspend
COMMON_GLOBAL_CFLAGS += -DBOARD_CHARGING_CMDLINE_NAME='"lge.reboot"' -DBOARD_CHARGING_CMDLINE_VALUE='"pwroff"'

TARGET_BOOTLOADER_BOARD_NAME := gelato
TARGET_OTA_ASSERT_DEVICE := gelato,vm701

#BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/lge/gelato/bluetooth

BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00500000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00700000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x09e00000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x0b500000
#twrp
DEVICE_RESOLUTION := 320x480
TW_CUSTOM_POWER_BUTTON := 107
TW_NO_REBOOT_BOOTLOADER := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGB_565"
